/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdRouteImport } from './routes/project/$id'
import { Route as ApiPresignUploadRouteImport } from './routes/api/presign-upload'
import { Route as ApiFetchAndUploadImageRouteImport } from './routes/api/fetch-and-upload-image'
import { Route as ApiPublicRenderCompleteRouteImport } from './routes/api/public/render-complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresignUploadRoute = ApiPresignUploadRouteImport.update({
  id: '/api/presign-upload',
  path: '/api/presign-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchAndUploadImageRoute = ApiFetchAndUploadImageRouteImport.update({
  id: '/api/fetch-and-upload-image',
  path: '/api/fetch-and-upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderCompleteRoute = ApiPublicRenderCompleteRouteImport.update({
  id: '/api/public/render-complete',
  path: '/api/public/render-complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/fetch-and-upload-image': typeof ApiFetchAndUploadImageRoute
  '/api/presign-upload': typeof ApiPresignUploadRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/public/render-complete': typeof ApiPublicRenderCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/fetch-and-upload-image': typeof ApiFetchAndUploadImageRoute
  '/api/presign-upload': typeof ApiPresignUploadRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/public/render-complete': typeof ApiPublicRenderCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/fetch-and-upload-image': typeof ApiFetchAndUploadImageRoute
  '/api/presign-upload': typeof ApiPresignUploadRoute
  '/project/$id': typeof ProjectIdRoute
  '/api/public/render-complete': typeof ApiPublicRenderCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/fetch-and-upload-image'
    | '/api/presign-upload'
    | '/project/$id'
    | '/api/public/render-complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/fetch-and-upload-image'
    | '/api/presign-upload'
    | '/project/$id'
    | '/api/public/render-complete'
  id:
    | '__root__'
    | '/'
    | '/api/fetch-and-upload-image'
    | '/api/presign-upload'
    | '/project/$id'
    | '/api/public/render-complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiFetchAndUploadImageRoute: typeof ApiFetchAndUploadImageRoute
  ApiPresignUploadRoute: typeof ApiPresignUploadRoute
  ProjectIdRoute: typeof ProjectIdRoute
  ApiPublicRenderCompleteRoute: typeof ApiPublicRenderCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id': {
      id: '/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presign-upload': {
      id: '/api/presign-upload'
      path: '/api/presign-upload'
      fullPath: '/api/presign-upload'
      preLoaderRoute: typeof ApiPresignUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-and-upload-image': {
      id: '/api/fetch-and-upload-image'
      path: '/api/fetch-and-upload-image'
      fullPath: '/api/fetch-and-upload-image'
      preLoaderRoute: typeof ApiFetchAndUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-complete': {
      id: '/api/public/render-complete'
      path: '/api/public/render-complete'
      fullPath: '/api/public/render-complete'
      preLoaderRoute: typeof ApiPublicRenderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiFetchAndUploadImageRoute: ApiFetchAndUploadImageRoute,
  ApiPresignUploadRoute: ApiPresignUploadRoute,
  ProjectIdRoute: ProjectIdRoute,
  ApiPublicRenderCompleteRoute: ApiPublicRenderCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
